# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: yn # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)





