#本地配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stock_01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/split/*.xml
  type-aliases-package: cn.chenxinfan.stock.domain


#多数据源参数
dataSource:
  config:
    dbNum: 2
    dbNameFormat: "%02d"
    dbDefaultNume: "default"
    tableNum: 2
    tableNameFormat: "%02d"
  db:
    config:
      default:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/stock_01?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
      db1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/stock_01?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
      db2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/stock_02?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456




